config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :employees
  resources :processos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/processo.rb
class Processo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	enum role: [:normal_user, :editor, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit

	protect_from_forgery with: :exception

	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	private
		def user_not_authorized
			flash[:notice] = "Você não tem permissão para fazer esta ação"
			redirect_to(request.referer || root_path) and return
		end

end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
	before_action :authenticate_user!

  def index
  	@control_users = User.all
  	authorize @control_users
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.page(params[:page]).per(10)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    authorize @employee
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    authorize @employee
  end

  # GET /employees/1/edit
  def edit
    authorize @employee
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Funcionário foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Funcionário foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
  	authorize @employee
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Funcionário foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :admitted_at, :occupation)
    end
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  before_action :set_processo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /processos
  # GET /processos.json
  def index
    @q = Processo.ransack(params[:q])
    @processos = @q.result

    @processos = @processos.page(params[:page]).per(10)
    authorize @processos
  end

  # GET /processos/1
  # GET /processos/1.json
  def show
    authorize @processo
  end

  # GET /processos/new
  def new
    @processo = Processo.new
    authorize @processo
  end

  # GET /processos/1/edit
  def edit
    authorize @processo
  end

  # POST /processos
  # POST /processos.json
  def create
    @processo = Processo.new(processo_params)

    respond_to do |format|
      if @processo.save
        format.html { redirect_to @processo, notice: 'Processo foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @processo }
      else
        format.html { render :new }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /processos/1
  # PATCH/PUT /processos/1.json
  def update
    respond_to do |format|
      if @processo.update(processo_params)
        format.html { redirect_to @processo, notice: 'Processo foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @processo }
      else
        format.html { render :edit }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processos/1
  # DELETE /processos/1.json
  def destroy
    authorize @processo
    @processo.destroy
    respond_to do |format|
      format.html { redirect_to processos_url, notice: 'Processo foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processo
      @processo = Processo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def processo_params
      params.require(:processo).permit(:process, :kind, :draft_date, :draft_author, :check_date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/control_users/index.html.erb
<%- model_class = ControlUsersController -%>

<table class="table table-striped">
  <thead>
    <tr>
      
      <th>Email</th>
      <th>Role</th>
      
      
    </tr>
  </thead>
  <tbody>
    <% @control_users.each do |users| %>
      <tr>
        
        <td><%= users.email %></td>
        <td><%= users.role %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/_form.html.erb
<%= form_for @employee, :html => { :class => "form-horizontal employee" } do |f| %>

  <% if @employee.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :admitted_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :admitted_at, :class => 'form-control', :type => 'date', :value => Date.today %>
    </div>
    <%=f.error_span(:admitted_at) %>
  </div>
  <div class="form-group">
    <%= f.label :occupation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :occupation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:occupation) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:admitted_at) %></th>
      <th><%= model_class.human_attribute_name(:occupation) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        
        <td><%= employee.name %></td>
        <td><%= employee.admitted_at %></td>
        <td><%= employee.occupation %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      employee_path(employee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-primary' %>
<%= paginate @employees %>
<%= page_entries_info @employees %>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @employee.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:admitted_at) %>:</strong></dt>
  <dd><%= @employee.admitted_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:occupation) %>:</strong></dt>
  <dd><%= @employee.occupation %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fórum" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Fórum</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <li><%= link_to current_user.email, root_path, :title => "Volta ao início" %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Cadastro de novo usuário", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Processos", processos_path  %></li>
              <li><%= link_to "Funcionários", employees_path  %></li>
              <li><%= link_to "Usuários", control_users_index_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p></p>
        <p>&copy; Cadu 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/processos/_form.html.erb
<%= form_for @processo, :html => { :class => "form-horizontal processo" } do |f| %>

  <% if @processo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@processo.errors.count, "error") %> prohibited this processo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @processo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :process, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :process, :class => 'form-control' %>
    </div>
    <%=f.error_span(:process) %>
  </div>
  <div class="form-group">
    <%= f.label :kind, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :kind, :class => 'form-control' %>
    </div>
    <%=f.error_span(:kind) %>
  </div>
  <div class="form-group">
    <%= f.label :draft_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :draft_date, :class => 'form-control', :type => 'date', :value => Date.today %>
    </div>
    <%=f.error_span(:draft_date) %>
  </div>
  <div class="form-group">
    <%= f.label :draft_author, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :draft_author, :class => 'form-control' %>
    </div>
    <%=f.error_span(:draft_author) %>
  </div>
  <div class="form-group">
    <%= f.label :check_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :check_date, :class => 'form-control', :type => 'date', :value => Date.today %>
    </div>
    <%=f.error_span(:check_date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                processos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/processos/edit.html.erb
<%- model_class = Processo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/processos/index.html.erb
<%- model_class = Processo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= search_form_for @q do |f| %>
    <div class="form-group">
      <%= label :search, :process , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.search_field :process_cont, :class => 'form-control' %>
    </div>
  </div>
    <div class="form-group">
      <%= label :search, :kind , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.search_field :kind_cont, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
      <%= label :search, :author , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.search_field :draft_author_cont, :class => 'form-control' %>
    </div>
  </div>
    <div class="form-group">
      <%= label :search, :from , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.search_field :check_date_gteq, :class => 'form-control', :type => 'date' %>
    </div>
  </div>
  <div class="form-group">
     <%= label :search, :until , :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
      <%= f.search_field :check_date_lteq, :class => 'form-control', :type => 'date' %>
    </div>
  </div>
    <div class="form-group">
     <%= f.submit nil, :class => 'btn btn-primary'  %>
    </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= sort_link(@q, :process) %></th>
      <th><%= sort_link(@q, :kind) %></th>
      <th><%= sort_link(@q, :draft_date) %></th>
      <th><%= sort_link(@q, :draft_author) %></th>
      <th><%= sort_link(@q, :check_date) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @processos.each do |processo| %>
      <tr>
        
        <td><%= processo.process %></td>
        <td><%= processo.kind %></td>
        <td><%= processo.draft_date %></td>
        <td><%= processo.draft_author %></td>
        <td><%= processo.check_date %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      processo_path(processo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_processo_path(processo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      processo_path(processo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @processos %>
<%= page_entries_info @processos %>
<br>

<div class="form-group">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_processo_path, :class => 'btn btn-primary' %>
</div>

app/views/processos/new.html.erb
<%- model_class = Processo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/processos/show.html.erb
<%- model_class = Processo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:process) %>:</strong></dt>
  <dd><%= @processo.process %></dd>
  <dt><strong><%= model_class.human_attribute_name(:kind) %>:</strong></dt>
  <dd><%= @processo.kind %></dd>
  <dt><strong><%= model_class.human_attribute_name(:draft_date) %>:</strong></dt>
  <dd><%= @processo.draft_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:draft_author) %>:</strong></dt>
  <dd><%= @processo.draft_author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:check_date) %>:</strong></dt>
  <dd><%= @processo.check_date %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              processos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_processo_path(@processo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              processo_path(@processo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>Bem Vindo</h1>